name: ci
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  test-node:
    name: Node ${{ matrix.node }} / ${{ matrix.os }}
    runs-on: anchor-3
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        node:
          - '18'
          - '16'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run build --if-present
      - run: npx eslint .
      - run: npm run test-node
  test-browser:
    name: Browser / ${{ matrix.browser }}
    runs-on: anchor-3
    strategy:
      fail-fast: false
      matrix:
        browser:
          - chromium
          - firefox
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '18'
      - run: npm install
      - run: npm run build --if-present
      - run: npm run test-browser-local
        env:
          BROWSER: ${{ matrix.browser }}